config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'movies#index'

  get 'matches/index'
  get 'landing/index'

  constraints subdomain: 'api' do
    namespace :api, path: '/' do
      resources :movies, only: [:index, :show]
    end
  end

  resources :movies do
    resources :theaters
    get :get, on: :collection
  end

  resources :users do
    get :history, on: :member
    resources :favorite_genres
    resources :favorite_movies
    resources :movie_nights

    resources :eliminated_movies
    resources :invite_friends do
      post :delete, on: :collection
    end
    resources :favorite_theaters do
      post :delete, on: :collection
    end
  end

  resources :movie_nights do
    resources :attendees, only: [:create, :destroy]
    resources :chats, only: [:create, :update]
  end

  resources :upcoming_movies, only: [:show]
  resources :out_movies, only: [:show]

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/movie_night.rb
class MovieNight < ActiveRecord::Base
  #has_paper_trail

  has_many :attendees
  has_many :users, through: :attendees, source: :user

  has_one :chat

  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  belongs_to :movie
  belongs_to :schedule

  scope :seen, ->{ where seen: true }

  def chat!
    chat.present? ? chat : build_chat(conversation: "[]")
  end
end

app/controllers/movie_nights_controller.rb
class MovieNightsController < ApplicationController
  def index
    @movie_nights = current_user.user_movie_nights
    @friends_movie_nights = current_user.friends_movie_nights
  end

  def create
    mov_night = current_user.user_movie_nights.new(movie_nights_params)
    if mov_night.save
    	@movies = MovieDecorator.build_with(
        Movie.in(country_code: current_country.code).playing_now_for(current_user))
    end
  end

  def update
    mov_night = current_user.user_movie_nights.find_by(movie_id: movie_nights_params["movie_id"])

    mov_night.destroy if params["commit"] == "movienight"
    mov_night.update(movie_nights_params) if params["commit"] == "seen"

    @movienight = MovieDecorator.build_with(current_user.movies.in_movienight)
  end

  def destroy
    movie_night = MovieNight.find params[:id]

    if current_user == movie_night.owner
      movie_night.destroy
      flash.notice = 'Movie Night successfully destroyed.'
    else
      flash.notice = 'Only the owner can destroy Movie Night'
    end
    redirect_to movie_nights_path
  end

  private
    def movie_nights_params
      params.require(:movie_night).permit(:movie_id)
    end
end

app/helpers/movie_nights_helper.rb
module MovieNightsHelper
end

app/views/movie_nights/_chat.html.haml
.chat
  .chat-view.content-message
    - movie_night.chat!.messages.each do |conversation|
      .conversaton
        .chat-user
          = conversation[:owner]
        .chat-message
          = conversation[:conversation]
  .new-message
    = image_tag "logo/small.png", class:"img-small"
    %p Vamos todos a ver
    .field-message
      = form_for [movie_night, movie_night.chat!] do |f|
        = f.text_field :conversation, value: ''
        = f.submit "Comentar"

app/views/movie_nights/_movie_night.html.haml
.movie-night.col-md-6
  =link_to movie_night.movie, id: movie_night.movie.id, remote: true do
    .mn-image
      .upcoming-movie
        .upcoming-poster
          = image_tag movie_night.movie.poster_path, class:"", width:"154px", height:"250px"
  .mn-desc
    .mn-desc-d
      %p.title CINE
      %span.edit EDITAR
      %p.cont= movie_night.movie.theaters.first.name
    .mn-desc-d
      %p.title FECHAS
      %span.edit EDITAR
      %p.cont= movie_night.movie.release_date
    .mn-desc-d
      %p.title HORARIOS
      %span.edit EDITAR
      %p.cont= movie_night.movie.schedules.first.description
    .mn-desc-d
      - if movie_night.owner == current_user
        = link_to 'Cancelar', movie_night, method: :delete, class: 'mn-action'
      - else
        - if movie_night.users.include? current_user
          = link_to 'Cancelo', movie_night_attendee_path(movie_night, current_user), method: :delete, class: 'mn-action'
        -else
          = form_for [movie_night, Attendee.new] do |f|
            = f.submit 'Unirse', class: 'mn-action'
    %p.center AMIGOS QUIEREN VER
    .row.center
      .mn-friends
        = image_tag movie_night.owner.image, class: 'prof-friend'
      - movie_night.users.each do |user|
        .mn-friends
          = image_tag user.image, class: 'prof-friend'
  .mn-chat.movie-night-left
    = render 'chat', movie_night: movie_night

app/views/movie_nights/_slider.html.haml
#movie-nights.row
	- @movie_nights.each do |movie_night|
		- next if movie_night.movie.poster_path.nil?
		= render 'movie_night', movie_night: movie_night

app/views/movie_nights/create.js.erb
$("#playing-now-slider").html("<%= j render 'movies/slider' %>")

$("#makeMeScrollable").smoothDivScroll({
  manualContinuousScrolling: true, 
  touchScrolling: true, 
  hotSpotMouseDownSpeedBooster: 1,
  hotSpotScrollingStep: 6
});

$('.movie-details').modal('hide');

app/views/movie_nights/index.html.haml
= content_for :nav_bottom do
  %li.nav-bottom
    = link_to "MOVIE NIGHTS", "#", {class: 'scrollit text-blue', 'data-target' => "#scroll_movie_nights"}
  %li.nav-bottom
    = link_to "PELIPALS", "#", {class: 'scrollit text-blue', 'data-target' => "#scroll_pelipals"}

.container-fluid
  .row-fluid
    .category#scroll_movie_nights
      %h4 MOVIE NIGHTS
      #watchlist-slider
        = render "movie_nights/slider"
  .row-fluid
    .category#scroll_pelipals
      %h4 PELIPALS
      #watchlist-slider
        = render "movie_night_friends/slider"
.modal-container

app/views/movie_nights/update.js.erb
$("#movienight-slider").html("<%= j render 'movie_nights/slider' %>")

$("#makeMeScrollable").smoothDivScroll({
  manualContinuousScrolling: true, 
  touchScrolling: true, 
  hotSpotMouseDownSpeedBooster: 1,
  hotSpotScrollingStep: 6
});

$('.movie-details').modal('hide');