config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'movies#index'

  get 'matches/index'
  get 'landing/index'

  constraints subdomain: 'api' do
    namespace :api, path: '/' do
      resources :movies, only: [:index, :show]
    end
  end

  resources :movies do
    resources :theaters
    get :get, on: :collection
  end

  resources :users do
    get :history, on: :member
    resources :favorite_genres
    resources :favorite_movies
    resources :movie_nights

    resources :eliminated_movies
    resources :invite_friends do
      post :delete, on: :collection
    end
    resources :favorite_theaters do
      post :delete, on: :collection
    end
  end

  resources :movie_nights do
    resources :attendees, only: [:create, :destroy]
    resources :chats, only: [:create, :update]
  end

  resources :upcoming_movies, only: [:show]
  resources :out_movies, only: [:show]

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/views/nav_bar/_countries.html.haml
%li.nav-top.dropdown.countries-dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#", title: "dropdown"}
    = image_tag("countries/flags/#{current_country.flag}.png", width: "25px")
    %span.caret
  %ul.dropdown-menu{role: "menu"}
    - Country.all.each do |country|
      %li= link_to country.name.upcase, {default_country: country.code}

app/views/nav_bar/_dropdown.html.haml
- if current_user
  %li.nav-top.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#", title: "user-dropdown"}
      = current_user.name
      %span.caret
    %ul.dropdown-menu{role: "menu"}
      %li= link_to "TUS CINES", user_favorite_theaters_path(current_user)
      %li= link_to "GENEROS", user_favorite_genres_path(current_user)
      %li= link_to "TUS AMIGOS", user_invite_friends_path(current_user)
      %li= link_to "HISTORIAL", history_user_path(current_user)
      %li= link_to "PELI PALS", "#"
      %li.divider
      - if current_user_is_an_admin?
        %li= link_to movie_match_helper, matches_index_path
        %li= link_to "ADMIN TOOL", rails_admin_path
        %li.divider
      %li= link_to "CERRAR SESION", signout_path, id: "sign_out"

- else
  = link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", class: "btn btn-primary"

app/views/nav_bar/_index.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .row-fluid
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .logo
          = link_to root_path do
            = image_tag "logo/normal.png", id:"logo"
      .collapse.navbar-collapse
        %ul.nav.navbar-nav
          = render 'nav_bar/links'
        %ul.nav.navbar-nav.navbar-right
          = render 'nav_bar/dropdown'
  .container-fluid.navbar-section.visible-lg-block.visible-md-block
    .row-fluid
      %ul.nav.navbar-nav
        = yield :nav_bottom

app/views/nav_bar/_links.html.haml
= render 'nav_bar/countries'

%li.nav-top{class: "#{'active' if current_page?(movies_path) or current_page?(root_path)}"}
  = link_to "CARTELERA", movies_path
%li.nav-top{class: "#{'active' if current_page?(user_favorite_movies_path(current_user))}"}
  = link_to "WATCHLIST", user_favorite_movies_path(current_user)
%li.nav-top{class: "#{'active' if current_page?(user_movie_nights_path(current_user))}"}
  = link_to "MOVIE NIGHT", user_movie_nights_path(current_user)